### ISSUE TITLE
What about frontend?

### ISSUE THREAD

**Issue by saileshkush95** [RamezIssac/django-tabular-permissions#11]
Thanks for this awesome plugins. This is working perfectly for django admin but what about frontend. I'm mean for cutstom admin panel.

**Comment by Filipe-Souza** [comment]
Hi @saileshkush95 

What kind of of front end you are suggesting? The permissions grid?

**Comment by saileshkush95** [comment]
Some things like below.
![Screenshot_20190812_235636](https://user-images.githubusercontent.com/28560875/62952088-cf658c80-be0a-11e9-87a0-0bd2e20a70d7.png)

**Comment by RamezIssac** [comment]
It would work no problem with a custom admin panel like any widget.
You can always adjust the css and for deeper control, you can always change how the grid is displayed completely by changing the template in your `settings.py`

    TABULAR_PERMISSIONS_CONFIG = {
        'template': 'MY-TEMPLATE-path/tabular_permissions.html',
    }
