### ISSUE TITLE
Implement tabular permissions in form

### ISSUE THREAD

**Issue by chaco88** [RamezIssac/django-tabular-permissions#16]
Hi, i like to know if it's possible implement this into a django form, thanks

**Comment by RamezIssac** [comment]
It's a Form in a HTML table widget.

If you want a different look, you can change / override the template `tabular_permissions/admin/tabular_permissions.html` and have a full control on how the widget will look like.

Did i answer your question ?

**Comment by chaco88** [comment]
no, i need show the permissions in a table in a custom form created by me

**Comment by RamezIssac** [comment]
Away from the admin user change page you mean? If so then no. :)
