### ISSUE TITLE
Doesn't work with custom User

### ISSUE THREAD

**Issue by donatogr** [RamezIssac/django-tabular-permissions#6]
If using custom User model (https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#substituting-a-custom-user-model)
I get an ImproperlyConfigured error because admin.py tries to unregister original model User instead of `get_user_model()`

**Comment by RamezIssac** [comment]
Version on Pypi have this issue, But it is fixed in the git repo... 
So kindly setup from the git repo, :) I should have released the new version on Pypi.

**Comment by RamezIssac** [comment]
django-tabular-permissions version 1.1 released on pypi
