### ISSUE TITLE
No repository for version 1.0.9

### ISSUE THREAD

**Issue by donatogr** [RamezIssac/django-tabular-permissions#8]
`pip` cannot find version 1.0.9, which is supposed to be the latest version working with Django < 1.11:

`  Could not find a version that satisfies the requirement django-tabular-permissions==1.0.9 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.1)
No matching distribution found for django-tabular-permissions==1.0.9`

**Comment by RamezIssac** [comment]
1.0.8 then i think :-)
